import csv


with open('input.csv', newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    finalCustomerDictionary = {}
    finalDateDictionary = {}
    finalProductnameDictionary = {}
    for row in reader:
        order_id = row['order_id']
        customer_id = row['customer_id']
        order_date = row['order_date']
        product_id = row['product_id']
        product_name = row['product_name']
        product_price = row['product_price']
        quantity = row['quantity']
        total_revenue = int(product_price) * int(quantity)
        if customer_id not in finalCustomerDictionary:
            finalCustomerDictionary[customer_id] = total_revenue
        else:
            finalCustomerDictionary[customer_id] = finalCustomerDictionary[customer_id] + total_revenue
        month_in_number = int(order_date.split('-')[1])
        if month_in_number == 1:
            month = "January"
        elif month_in_number == 2:
            month = "February"
        elif month_in_number == 3:
            month = "March"
        elif month_in_number == 4:
            month = "April"
        elif month_in_number == 5:
            month = "May"
        elif month_in_number == 6:
            month = "June"
        elif month_in_number == 7:
            month = "July"
        elif month_in_number == 8:
            month = "August"
        elif month_in_number == 9:
            month = "September"
        elif month_in_number == 10:
            month = "October"
        elif month_in_number == 11:
            month = "November"
        elif month_in_number == 12:
            month = "December"                                        
            
        if month not in finalDateDictionary:
            finalDateDictionary[month] = total_revenue
        else:
            finalDateDictionary[month] = finalDateDictionary[month] + total_revenue 

        if product_name not in finalProductnameDictionary:
            finalProductnameDictionary[product_name] = total_revenue
        else:
            finalProductnameDictionary[product_name] = finalProductnameDictionary[product_name] + total_revenue 

print("Compute the total revenue generated by the online store for each month in the dataset = {}".format(finalDateDictionary)) 
print("Compute the total revenue generated by each product in the dataset = {}".format(finalProductnameDictionary))
print("Compute the total revenue generated by each customer in the dataset = {}".format(finalCustomerDictionary))
print("Identify the top 10 customers by revenue generated = {}".format(sorted(finalCustomerDictionary,reverse=True)[:10]))            




  
 